# Generated by Django 2.2.13 on 2020-10-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('players', models.CharField(max_length=1000)),
                ('coach', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
            ],
        ),
    ]
