# Generated by Django 2.2.13 on 2020-10-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballapp', '0002_teammatches'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatches',
            name='team_a_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teammatches',
            name='team_b_points',
            field=models.IntegerField(null=True),
        ),
    ]
